{{- if .Values.datasources.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "client.fullname" . }}-clickhouse-datasource
  labels:
    {{ .Values.datasources.label }}: {{ .Values.datasources.labelValue | quote }}
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: ClickHouse
        type: grafana-clickhouse-datasource
        jsonData:
          port: 9000
          server: {{ include "client.fullname" . }}-clickhouse
          tlsSkipVerify: true
{{- end }}