{{- if .Values.datasources.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "client.fullname" . }}-vertamedia-datasource
  labels:
    {{ .Values.datasources.label }}: {{ .Values.datasources.labelValue | quote }}
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: vertamedia-clickhouse-datasource
        type: vertamedia-clickhouse-datasource
        url: {{ include "client.fullname" . }}-clickhouse:8123
        access: proxy
{{- end }}