{{- if .Values.externalSecrets.create }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nats-external
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: nats-secret
  data:
  - secretKey: nats-token
    remoteRef:
      key: secret/generic/nats/auth-token
      property: nats
{{- end }}